In [1]:
import pandas as pd
import openpyxl

In [2]:
data = pd.read_csv('23-09-risk-guatemala/confirmados-desde-2020-08-25-a-2020-09-23.csv')
data.head()

,departamento,codigo_departamento,municipio,codigo_municipio,poblacion,2020-08-25,2020-08-26,2020-08-27,2020-08-28,2020-08-29,...,2020-09-15,2020-09-16,2020-09-17,2020-09-18,2020-09-19,2020-09-20,2020-09-21,2020-09-22,2020-09-23,2020-09-24
0,ALTA VERAPAZ,16,CAHABON,1612,69107,3,3,1,1,1,...,0,2,4,0,0,0,0,0,0,0
1,ALTA VERAPAZ,16,CHISEC,1613,104428,1,0,0,0,1,...,0,0,0,0,0,0,0,2,1,0
2,ALTA VERAPAZ,16,COBAN,1601,224109,8,22,20,16,12,...,17,25,4,16,14,2,15,5,12,4
3,ALTA VERAPAZ,16,FRAY BARTOLOME DE LAS CASAS,1615,76047,7,2,3,0,0,...,1,0,1,0,1,2,1,3,1,0
4,ALTA VERAPAZ,16,LANQUIN,1611,26146,1,1,0,0,1,...,0,0,1,0,0,0,0,1,0,0

In [3]:
data.shape

(332, 36)

In [4]:
data.isnull().values.sum(axis = 0)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
data.fillna(0, inplace = True)

In [6]:
data.isnull()

,departamento,codigo_departamento,municipio,codigo_municipio,poblacion,2020-08-25,2020-08-26,2020-08-27,2020-08-28,2020-08-29,...,2020-09-15,2020-09-16,2020-09-17,2020-09-18,2020-09-19,2020-09-20,2020-09-21,2020-09-22,2020-09-23,2020-09-24
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
327,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
328,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
329,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
330,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
331,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [7]:
data['departamento'].value_counts().count()
#24 departamentos

23

In [8]:
data['codigo_departamento'].value_counts().count()
#23 codigo departamentos, uno esta errado

23

In [9]:
data['municipio'].value_counts().count()
#214 municipios

324

In [10]:
data['codigo_municipio'].value_counts().count()
#208 cod municipios, 6 estan errados

328

In [11]:
data['municipio'].value_counts()

SIN DATOS                 4
SAN LORENZO               2
LA LIBERTAD               2
LA DEMOCRACIA             2
SAN PEDRO SACATEPEQUEZ    2
                         ..
SAN PEDRO CARCHA          1
HUITAN                    1
BARILLAS                  1
SANTA CRUZ BALANYA        1
MONJAS                    1
Name: municipio, Length: 324, dtype: int64

In [12]:
# Se decidio implementarlo por municipio, se procede a normalizar la data

In [13]:
data.head()

,departamento,codigo_departamento,municipio,codigo_municipio,poblacion,2020-08-25,2020-08-26,2020-08-27,2020-08-28,2020-08-29,...,2020-09-15,2020-09-16,2020-09-17,2020-09-18,2020-09-19,2020-09-20,2020-09-21,2020-09-22,2020-09-23,2020-09-24
0,ALTA VERAPAZ,16,CAHABON,1612,69107,3,3,1,1,1,...,0,2,4,0,0,0,0,0,0,0
1,ALTA VERAPAZ,16,CHISEC,1613,104428,1,0,0,0,1,...,0,0,0,0,0,0,0,2,1,0
2,ALTA VERAPAZ,16,COBAN,1601,224109,8,22,20,16,12,...,17,25,4,16,14,2,15,5,12,4
3,ALTA VERAPAZ,16,FRAY BARTOLOME DE LAS CASAS,1615,76047,7,2,3,0,0,...,1,0,1,0,1,2,1,3,1,0
4,ALTA VERAPAZ,16,LANQUIN,1611,26146,1,1,0,0,1,...,0,0,1,0,0,0,0,1,0,0

In [14]:
# Solo municipios de guatemala
df_dep = data[data['departamento'] == 'GUATEMALA']
df_dep['municipio'].value_counts().count()

17

In [15]:
df_dep = df_dep.drop(columns = ['codigo_departamento', 'codigo_municipio', 'poblacion', 'departamento'],
                  axis = 1)
df_dep['municipio'] = df_dep['municipio'].str.title()
df_dep.head()

,municipio,2020-08-25,2020-08-26,2020-08-27,2020-08-28,2020-08-29,2020-08-30,2020-08-31,2020-09-01,2020-09-02,...,2020-09-15,2020-09-16,2020-09-17,2020-09-18,2020-09-19,2020-09-20,2020-09-21,2020-09-22,2020-09-23,2020-09-24
31,Amatitlan,3,5,8,1,0,0,7,4,1,...,3,1,2,4,2,1,6,1,2,3
32,Chinautla,1,8,5,1,0,1,1,1,0,...,2,6,2,2,0,1,0,5,2,2
33,Fraijanes,3,8,7,5,1,2,4,4,11,...,1,4,3,3,7,2,4,0,0,0
34,Guatemala,135,137,106,105,81,45,120,107,88,...,60,93,73,97,79,40,97,66,40,23
35,Mixco,30,33,43,39,19,3,33,28,33,...,13,26,31,32,25,20,29,14,8,5

In [16]:
# tenemos 198 filas pero 24 departamentos diferentes
# se procede a combinar filas y obtener la sumatoria
# Pivot: se realiza el traslado de columnas por filas para obtener la sumatoria por dep.
total_columnas = df_dep.columns[1:].to_numpy()
#total_filas = df_dep['departamento'][total_filas].keys().to_numpy()
#sumarize rows
df = df_dep.groupby('municipio').sum()
#df_dep_p = pd.DataFrame(df_dep[total_columnas].values.reshape(1,-1), 
 #                   index=['Market 1 Order'], 
  #                  columns=total_filas)
df.head()

,2020-08-25,2020-08-26,2020-08-27,2020-08-28,2020-08-29,2020-08-30,2020-08-31,2020-09-01,2020-09-02,2020-09-03,...,2020-09-15,2020-09-16,2020-09-17,2020-09-18,2020-09-19,2020-09-20,2020-09-21,2020-09-22,2020-09-23,2020-09-24
municipio,,,,,,,,,,,,,,,,,,,,,
Amatitlan,3,5,8,1,0,0,7,4,1,1,...,3,1,2,4,2,1,6,1,2,3
Chinautla,1,8,5,1,0,1,1,1,0,4,...,2,6,2,2,0,1,0,5,2,2
Fraijanes,3,8,7,5,1,2,4,4,11,6,...,1,4,3,3,7,2,4,0,0,0
Guatemala,135,137,106,105,81,45,120,107,88,82,...,60,93,73,97,79,40,97,66,40,23
Mixco,30,33,43,39,19,3,33,28,33,26,...,13,26,31,32,25,20,29,14,8,5

In [17]:
final_df = df.transpose()
final_df.rename(columns={'departamento':'date'},inplace= True)

In [18]:
final_df.drop("Sin Datos", axis=1, inplace=True)
final_df.drop("Sin Dato", axis=1, inplace=True)
final_df.drop("Otros", axis=1, inplace=True)

KeyError: "['Sin Dato'] not found in axis"

In [19]:
# Crear columna Total
final_df['Total'] = final_df.sum(axis = 1)

In [20]:
final_df.head(29)

municipio,Amatitlan,Chinautla,Fraijanes,Guatemala,Mixco,Palencia,San Jose Del Golfo,San Jose Pinula,San Juan Sacatepequez,San Miguel Petapa,San Pedro Ayampuc,San Pedro Sacatepequez,San Raymundo,Santa Catarina Pinula,Villa Canales,Villa Nueva,Total
2020-08-25,3,1,3,135,30,2,0,5,1,11,2,0,1,5,5,18,222
2020-08-26,5,8,8,137,33,2,0,1,2,11,3,0,1,2,4,14,231
2020-08-27,8,5,7,106,43,1,1,10,9,5,0,0,7,6,7,18,233
2020-08-28,1,1,5,105,39,2,0,3,4,5,2,0,2,5,3,16,193
2020-08-29,0,0,1,81,19,0,0,1,4,4,1,1,0,6,2,3,123
2020-08-30,0,1,2,45,3,1,0,2,2,1,1,1,0,2,3,3,67
2020-08-31,7,1,4,120,33,2,0,4,2,6,1,0,0,8,4,19,211
2020-09-01,4,1,4,107,28,0,0,6,6,11,0,0,1,5,2,17,192
2020-09-02,1,0,11,88,33,1,0,5,2,7,0,0,0,1,1,15,165
2020-09-03,1,4,6,82,26,0,0,10,4,17,1,0,0,10,4,15,180
2020-09-04,1,2,5,95,24,0,0,2,4,5,1,4,0,6,5,19,173
2020-09-05,2,1,2,55,22,1,1,3,3,4,0,0,0,3,0,7,104
2020-09-06,1,0,7,50,12,0,0,4,1,2,0,0,0,4,1,3,85
2020-09-07,4,3,4,94,34,0,0,8,3,6,1,1,0,7,4,14,183
2020-09-08,7,3,2,112,29,1,0,2,3,4,2,1,0,4,6,16,192
2020-09-09,4,1,6,76,30,1,0,4,5,8,0,0,1,5,6,9,156
2020-09-10,2,2,3,82,26,4,0,4,2,14,2,0,0,11,2,24,178
2020-09-11,6,6,4,60,32,3,0,12,1,5,5,0,1,6,1,14,156
2020-09-12,0,0,2,63,32,2,0,4,1,13,3,0,0,3,1,10,134
2020-09-13,2,3,3,43,9,0,0,3,1,2,10,1,0,1,1,6,85
2020-09-14,4,4,3,90,24,0,0,9,6,10,4,1,2,5,2,16,180
2020-09-15,3,2,1,60,13,2,2,4,1,2,3,0,1,11,3,3,111
2020-09-16,1,6,4,93,26,0,0,3,3,8,4,1,0,7,2,16,174
2020-09-17,2,2,3,73,31,0,3,14,6,4,0,1,5,3,4,10,161
2020-09-18,4,2,3,97,32,0,2,9,4,12,4,0,2,10,5,22,208
2020-09-19,2,0,7,79,25,3,0,13,4,9,2,0,0,8,3,8,163
2020-09-20,1,1,2,40,20,0,0,7,0,3,1,0,1,4,0,4,84
2020-09-21,6,0,4,97,29,3,0,4,4,3,6,1,0,19,2,15,193
2020-09-22,1,5,0,66,14,2,0,6,1,4,1,0,0,7,1,15,123

In [21]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 31 entries, 2020-08-25 to 2020-09-24
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Amatitlan               31 non-null     int64
 1   Chinautla               31 non-null     int64
 2   Fraijanes               31 non-null     int64
 3   Guatemala               31 non-null     int64
 4   Mixco                   31 non-null     int64
 5   Palencia                31 non-null     int64
 6   San Jose Del Golfo      31 non-null     int64
 7   San Jose Pinula         31 non-null     int64
 8   San Juan Sacatepequez   31 non-null     int64
 9   San Miguel Petapa       31 non-null     int64
 10  San Pedro Ayampuc       31 non-null     int64
 11  San Pedro Sacatepequez  31 non-null     int64
 12  San Raymundo            31 non-null     int64
 13  Santa Catarina Pinula   31 non-null     int64
 14  Villa Canales           31 non-null     int64
 15  Villa Nueva             31 non-null     int64
 16  Total                   31 non-null     int64
dtypes: int64(17)
memory usage: 4.4+ KB

final = pd.DataFrame(final_df)
import numpy as np
df_total = final
df_total.loc['Total',:]= final.sum(axis=0)
df_total = df_total.iloc[[-1]]
totales = pd.DataFrame([[24,15,60,23,22,227,1606,17,88,4,15,24,126,15,39,99,85,23,0,25,88,40,44]], columns=['Alta Verapaz', 'Baja Verapaz', 'Chimaltenango', 'Chiquimula',
       'El Progreso', 'Escuintla', 'Guatemala', 'Huehuetenango', 'Izabal',
       'Jalapa', 'Jutiapa', 'Peten', 'Quetzaltenango', 'Quiche', 'Retalhuleu',
       'Sacatepequez', 'San Marcos', 'Santa Rosa', 'Sin Dato', 'Solola',
       'Suchitepequez', 'Totonicapan', 'Zacapa'])
totales.columns

In [22]:
# Exportar excel
final_df.to_excel(r'D:\Work\Guatemala\envios\23-09-map-risk-and-others-plots\de-25-08-2020-a-23-09-2020-casos-x-municipio-guatemala.xlsx')

In [23]:
final_df.head()

municipio,Amatitlan,Chinautla,Fraijanes,Guatemala,Mixco,Palencia,San Jose Del Golfo,San Jose Pinula,San Juan Sacatepequez,San Miguel Petapa,San Pedro Ayampuc,San Pedro Sacatepequez,San Raymundo,Santa Catarina Pinula,Villa Canales,Villa Nueva,Total
2020-08-25,3,1,3,135,30,2,0,5,1,11,2,0,1,5,5,18,222
2020-08-26,5,8,8,137,33,2,0,1,2,11,3,0,1,2,4,14,231
2020-08-27,8,5,7,106,43,1,1,10,9,5,0,0,7,6,7,18,233
2020-08-28,1,1,5,105,39,2,0,3,4,5,2,0,2,5,3,16,193
2020-08-29,0,0,1,81,19,0,0,1,4,4,1,1,0,6,2,3,123

In [24]:
total_columnas = final_df.columns.values
total_columnas

array(['Amatitlan', 'Chinautla', 'Fraijanes', 'Guatemala', 'Mixco',
       'Palencia', 'San Jose Del Golfo', 'San Jose Pinula',
       'San Juan Sacatepequez', 'San Miguel Petapa', 'San Pedro Ayampuc',
       'San Pedro Sacatepequez', 'San Raymundo', 'Santa Catarina Pinula',
       'Villa Canales', 'Villa Nueva', 'Total'], dtype=object)

In [25]:
final_df1 = final_df
for column in total_columnas:
    for idx, value in enumerate(final_df1[column]):
        if idx == 0:
            continue
        final_df1[column].iloc[idx] = final_df1[column].iloc[idx] + final_df1[column].iloc[idx - 1]

In [26]:
# Crear columna Total
final_df1['Total'] = final_df1.sum(axis = 1)

In [27]:
final_df1.to_excel(r'D:\Work\Guatemala\envios\23-09-map-risk-and-others-plots\de-25-08-2020-a-23-09-2020-casos-x-municipio-guatemala-acumulada.xlsx')